"""initial migration

Revision ID: 36820ac0fa4e
Revises: 
Create Date: 2024-02-08 22:03:24.240228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36820ac0fa4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('debtor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('creditor_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['creditor_id'], ['user.telegram_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('loan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount_of_debt', sa.Integer(), nullable=False),
    sa.Column('subject_of_debt', sa.String(), nullable=False),
    sa.Column('date_of_loan', sa.Date(), nullable=False),
    sa.Column('end_date_of_loan', sa.Date(), nullable=True),
    sa.Column('is_debt_repaid', sa.Boolean(), nullable=True),
    sa.Column('creditor_id', sa.BigInteger(), nullable=False),
    sa.Column('debtor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creditor_id'], ['user.telegram_id'], ),
    sa.ForeignKeyConstraint(['debtor_id'], ['debtor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan')
    op.drop_table('debtor')
    op.drop_table('user')
    # ### end Alembic commands ###
